import os
import secrets
from collections import deque
from email.header import decode_header
from urllib.parse import urlencode

import asyncpg
import httpx

from fastapi import (
    BackgroundTasks,
    FastAPI,
    HTTPException,
    Request,
)

from fastapi.responses import (
    HTMLResponse,
    PlainTextResponse,
    RedirectResponse,
)

from pydantic import BaseModel
from dotenv import load_dotenv

from agent import run_agent


# =========================================================
# Load environment
# =========================================================

load_dotenv()

app = FastAPI(
    title="Amir Personal AI"
)


# =========================================================
# Environment Variables
# =========================================================

GOOGLE_CLIENT_ID = os.getenv(
    "GOOGLE_CLIENT_ID"
)

GOOGLE_CLIENT_SECRET = os.getenv(
    "GOOGLE_CLIENT_SECRET"
)

GOOGLE_REFRESH_TOKEN = os.getenv(
    "GOOGLE_REFRESH_TOKEN"
)

WHATSAPP_ACCESS_TOKEN = os.getenv(
    "WHATSAPP_ACCESS_TOKEN"
)

WHATSAPP_PHONE_NUMBER_ID = os.getenv(
    "WHATSAPP_PHONE_NUMBER_ID"
)

WHATSAPP_VERIFY_TOKEN = os.getenv(
    "WHATSAPP_VERIFY_TOKEN",
    "amir_personal_ai_verify_2026",
)

DATABASE_URL = os.getenv(
    "DATABASE_URL"
)

REDIRECT_URI = (
    "https://amir-personal-ai-agent.onrender.com/"
    "auth/google/callback"
)

GMAIL_SCOPE = (
    "https://www.googleapis.com/"
    "auth/gmail.readonly"
)


# =========================================================
# Google temporary memory
# =========================================================

pending_states = set()

google_tokens = {}


# =========================================================
# Database
# =========================================================

db_pool = None


async def connect_database():

    global db_pool

    if not DATABASE_URL:

        print(
            "DATABASE_URL is not configured"
        )

        return

    try:

        db_pool = await asyncpg.create_pool(
            dsn=DATABASE_URL,
            min_size=1,
            max_size=3,
            command_timeout=30,
        )

        async with db_pool.acquire() as conn:

            await conn.execute(
                """
                create table if not exists agent_memory (
                    id bigint generated by default
                    as identity primary key,

                    phone_number text not null,

                    role text not null,

                    content text not null,

                    created_at timestamptz
                    default now()
                );
                """
            )

            await conn.execute(
                """
                create index if not exists
                idx_agent_memory_phone
                on agent_memory (
                    phone_number,
                    created_at desc
                );
                """
            )

        print(
            "Supabase database connected successfully"
        )

    except Exception as exc:

        db_pool = None

        print(
            "Database connection error:",
            repr(exc),
        )


@app.on_event("startup")
async def startup_event():

    await connect_database()


@app.on_event("shutdown")
async def shutdown_event():

    global db_pool

    if db_pool:

        await db_pool.close()

        db_pool = None


# =========================================================
# Persistent Conversation Memory
# =========================================================

MAX_CONVERSATION_MESSAGES = 20


async def save_memory(
    user_id: str,
    role: str,
    content: str,
):

    if (
        not user_id
        or not role
        or not content
    ):

        return

    if not db_pool:

        print(
            "Memory not saved: "
            "database unavailable"
        )

        return

    try:

        async with db_pool.acquire() as conn:

            await conn.execute(
                """
                insert into agent_memory (
                    phone_number,
                    role,
                    content
                )

                values (
                    $1,
                    $2,
                    $3
                )
                """,
                user_id,
                role,
                content,
            )

    except Exception as exc:

        print(
            "Memory save error:",
            repr(exc),
        )


async def get_memory(
    user_id: str,
    limit: int = MAX_CONVERSATION_MESSAGES,
):

    if not user_id:

        return []

    if not db_pool:

        return []

    try:

        async with db_pool.acquire() as conn:

            rows = await conn.fetch(
                """
                select
                    role,
                    content,
                    created_at

                from agent_memory

                where phone_number = $1

                order by created_at desc

                limit $2
                """,
                user_id,
                limit,
            )

        result = []

        for row in reversed(rows):

            result.append(
                {
                    "role": row["role"],
                    "content": row["content"],
                }
            )

        return result

    except Exception as exc:

        print(
            "Memory read error:",
            repr(exc),
        )

        return []


async def build_conversation_context(
    user_id: str,
) -> str:

    history = await get_memory(
        user_id
    )

    if not history:

        return ""

    lines = []

    for item in history:

        role = item.get(
            "role"
        )

        content = item.get(
            "content",
            "",
        )

        if role == "user":

            label = "المستخدم"

        else:

            label = "المساعد"

        lines.append(
            f"{label}: {content}"
        )

    return "\n".join(
        lines
    )


# =========================================================
# WhatsApp duplicate protection
# =========================================================

MAX_PROCESSED_WHATSAPP_MESSAGES = 1000

processed_whatsapp_message_ids = set()

processed_whatsapp_message_order = deque()


def remember_whatsapp_message(
    message_id: str,
) -> bool:

    if not message_id:

        return True

    if (
        message_id
        in processed_whatsapp_message_ids
    ):

        return False

    processed_whatsapp_message_ids.add(
        message_id
    )

    processed_whatsapp_message_order.append(
        message_id
    )

    while (
        len(
            processed_whatsapp_message_order
        )
        > MAX_PROCESSED_WHATSAPP_MESSAGES
    ):

        oldest_id = (
            processed_whatsapp_message_order
            .popleft()
        )

        processed_whatsapp_message_ids.discard(
            oldest_id
        )

    return True


# =========================================================
# Models
# =========================================================

class ChatRequest(BaseModel):

    message: str


# =========================================================
# Root / Health
# =========================================================

@app.get("/")
def root():

    return {
        "name": "Amir Personal AI",
        "status": "online",

        "database": (
            "connected"
            if db_pool
            else "disconnected"
        ),

        "gmail_login": (
            "/auth/google"
        ),

        "gmail_status": (
            "/gmail/status"
        ),

        "gmail_messages": (
            "/gmail/messages"
        ),

        "whatsapp_webhook": (
            "/whatsapp/webhook"
        ),

        "health": (
            "/health"
        ),
    }


@app.get("/health")
def health():

    return {
        "status": "ok",

        "database_connected": bool(
            db_pool
        ),

        "gmail_refresh_token_configured": bool(
            GOOGLE_REFRESH_TOKEN
        ),
    }


# =========================================================
# Privacy
# =========================================================

@app.get(
    "/privacy",
    response_class=HTMLResponse,
)
def privacy():

    return """
    <!doctype html>

    <html lang="ar" dir="rtl">

    <head>

        <meta charset="utf-8">

        <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
        >

        <title>
            سياسة الخصوصية
        </title>

    </head>

    <body style="
        font-family:Arial;
        max-width:800px;
        margin:40px auto;
        padding:20px;
        line-height:1.8;
    ">

        <h1>
            سياسة الخصوصية
        </h1>

        <p>
            يستخدم التطبيق Google OAuth
            للوصول إلى Gmail بإذن المستخدم.
        </p>

        <p>
            الوصول إلى Gmail للقراءة فقط.
        </p>

        <p>
            يستخدم التطبيق WhatsApp Cloud API
            لاستقبال والرد على الرسائل.
        </p>

        <p>
            قد يتم حفظ سجل المحادثة
            لتوفير ذاكرة مستمرة للمساعد.
        </p>

    </body>

    </html>
    """


# =========================================================
# Terms
# =========================================================

@app.get(
    "/terms",
    response_class=HTMLResponse,
)
def terms():

    return """
    <!doctype html>

    <html lang="ar" dir="rtl">

    <head>

        <meta charset="utf-8">

        <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
        >

        <title>
            شروط الاستخدام
        </title>

    </head>

    <body style="
        font-family:Arial;
        max-width:800px;
        margin:40px auto;
        padding:20px;
        line-height:1.8;
    ">

        <h1>
            شروط الاستخدام
        </h1>

        <p>
            هذا التطبيق مساعد شخصي
            للمستخدمين المصرح لهم.
        </p>

    </body>

    </html>
    """


# =========================================================
# Gmail Helpers
# =========================================================

def decode_mime_header(
    value: str,
) -> str:

    if not value:

        return ""

    try:

        parts = decode_header(
            value
        )

        result = ""

        for (
            part,
            encoding,
        ) in parts:

            if isinstance(
                part,
                bytes,
            ):

                result += part.decode(
                    encoding or "utf-8",
                    errors="replace",
                )

            else:

                result += part

        return result

    except Exception:

        return value


def repair_mojibake(
    text: str,
) -> str:

    if not text:

        return ""

    candidates = [
        text
    ]

    for source_encoding in [
        "latin1",
        "cp1252",
    ]:

        try:

            fixed = (
                text
                .encode(
                    source_encoding,
                    errors="ignore",
                )
                .decode(
                    "utf-8",
                    errors="ignore",
                )
            )

            if fixed:

                candidates.append(
                    fixed
                )

        except Exception:

            pass

    def score(
        value: str,
    ) -> int:

        bad = (
            value.count("Ø")
            + value.count("Ù")
            + value.count("Ã")
            + value.count("â€")
            + value.count("�")
        )

        arabic = sum(
            1
            for char in value
            if "\u0600"
            <= char
            <= "\u06ff"
        )

        return (
            arabic * 3
            - bad * 5
        )

    return max(
        candidates,
        key=score,
    )


def clean_header(
    value: str,
) -> str:

    return repair_mojibake(
        decode_mime_header(
            value
        )
    )


def get_header(
    headers: list,
    name: str,
) -> str:

    for header in headers:

        if (
            header
            .get(
                "name",
                "",
            )
            .lower()
            == name.lower()
        ):

            return clean_header(
                header.get(
                    "value",
                    "",
                )
            )

    return ""


# =========================================================
# Google OAuth
# =========================================================

async def refresh_access_token() -> str:

    refresh_token = (
        google_tokens.get(
            "refresh_token"
        )
        or GOOGLE_REFRESH_TOKEN
    )

    if not refresh_token:

        raise HTTPException(
            status_code=401,
            detail=(
                "Connect Gmail first"
            ),
        )

    if (
        not GOOGLE_CLIENT_ID
        or not GOOGLE_CLIENT_SECRET
    ):

        raise HTTPException(
            status_code=500,
            detail=(
                "Google OAuth "
                "is not configured"
            ),
        )

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:

        response = await client.post(
            "https://oauth2.googleapis.com/token",

            data={
                "client_id": (
                    GOOGLE_CLIENT_ID
                ),

                "client_secret": (
                    GOOGLE_CLIENT_SECRET
                ),

                "refresh_token": (
                    refresh_token
                ),

                "grant_type": (
                    "refresh_token"
                ),
            },
        )

    if response.status_code != 200:

        # Do not print the complete Google response
        # because it may contain sensitive details.

        print(
            "Google token refresh failed:",
            response.status_code,
        )

        raise HTTPException(
            status_code=401,
            detail=(
                "تعذر تجديد جلسة Gmail"
            ),
        )

    token_data = response.json()

    access_token = token_data.get(
        "access_token"
    )

    if not access_token:

        raise HTTPException(
            status_code=401,
            detail=(
                "Google did not return "
                "an access token"
            ),
        )

    google_tokens[
        "access_token"
    ] = access_token

    google_tokens[
        "refresh_token"
    ] = refresh_token

    return access_token


async def get_access_token() -> str:

    access_token = google_tokens.get(
        "access_token"
    )

    if access_token:

        return access_token

    return await refresh_access_token()


@app.get(
    "/auth/google"
)
def google_login():

    if (
        not GOOGLE_CLIENT_ID
        or not GOOGLE_CLIENT_SECRET
    ):

        raise HTTPException(
            status_code=500,
            detail=(
                "Google OAuth "
                "is not configured"
            ),
        )

    state = secrets.token_urlsafe(
        32
    )

    pending_states.add(
        state
    )

    params = {

        "client_id": (
            GOOGLE_CLIENT_ID
        ),

        "redirect_uri": (
            REDIRECT_URI
        ),

        "response_type": (
            "code"
        ),

        "scope": (
            GMAIL_SCOPE
        ),

        "access_type": (
            "offline"
        ),

        "prompt": (
            "consent"
        ),

        "state": (
            state
        ),
    }

    url = (
        "https://accounts.google.com/"
        "o/oauth2/v2/auth?"
        + urlencode(
            params
        )
    )

    return RedirectResponse(
        url
    )


@app.get(
    "/auth/google/callback"
)
async def google_callback(
    code: str,
    state: str,
):

    if (
        state
        not in pending_states
    ):

        raise HTTPException(
            status_code=400,
            detail=(
                "Invalid OAuth state"
            ),
        )

    pending_states.remove(
        state
    )

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:

        response = await client.post(
            "https://oauth2.googleapis.com/token",

            data={
                "client_id": (
                    GOOGLE_CLIENT_ID
                ),

                "client_secret": (
                    GOOGLE_CLIENT_SECRET
                ),

                "code": (
                    code
                ),

                "grant_type": (
                    "authorization_code"
                ),

                "redirect_uri": (
                    REDIRECT_URI
                ),
            },
        )

    if response.status_code != 200:

        print(
            "Google authorization failed:",
            response.status_code,
        )

        raise HTTPException(
            status_code=400,
            detail=(
                "Google authorization failed"
            ),
        )

    token_data = response.json()

    access_token = token_data.get(
        "access_token"
    )

    refresh_token = token_data.get(
        "refresh_token"
    )

    if access_token:

        google_tokens[
            "access_token"
        ] = access_token

    if refresh_token:

        google_tokens[
            "refresh_token"
        ] = refresh_token

    return PlainTextResponse(
        "Gmail connected successfully"
    )


# =========================================================
# Gmail API Request
# =========================================================

async def gmail_request(
    method: str,
    url: str,
    **kwargs,
):

    access_token = await get_access_token()

    headers = kwargs.pop(
        "headers",
        {},
    )

    headers[
        "Authorization"
    ] = (
        f"Bearer {access_token}"
    )

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:

        response = await client.request(
            method,
            url,
            headers=headers,
            **kwargs,
        )

    if response.status_code == 401:

        google_tokens.pop(
            "access_token",
            None,
        )

        access_token = (
            await refresh_access_token()
        )

        headers[
            "Authorization"
        ] = (
            f"Bearer {access_token}"
        )

        async with httpx.AsyncClient(
            timeout=30.0
        ) as client:

            response = await client.request(
                method,
                url,
                headers=headers,
                **kwargs,
            )

    return response


# =========================================================
# Gmail Status
# =========================================================

@app.get(
    "/gmail/status"
)
async def gmail_status():

    try:

        response = await gmail_request(
            "GET",
            (
                "https://gmail.googleapis.com/"
                "gmail/v1/users/me/profile"
            ),
        )

        if response.status_code != 200:

            return {
                "connected": False,
                "status_code": (
                    response.status_code
                ),
                "persistent_refresh_token": bool(
                    GOOGLE_REFRESH_TOKEN
                ),
            }

        data = response.json()

        return {
            "connected": True,

            "email": data.get(
                "emailAddress"
            ),

            "persistent_refresh_token": bool(
                GOOGLE_REFRESH_TOKEN
            ),
        }

    except HTTPException as exc:

        return {
            "connected": False,
            "error": exc.detail,

            "persistent_refresh_token": bool(
                GOOGLE_REFRESH_TOKEN
            ),
        }

    except Exception as exc:

        print(
            "Gmail status error:",
            repr(exc),
        )

        return {
            "connected": False,
            "error": (
                "Gmail status check failed"
            ),

            "persistent_refresh_token": bool(
                GOOGLE_REFRESH_TOKEN
            ),
        }


# =========================================================
# Gmail Summaries
# =========================================================

async def get_gmail_summaries(
    limit: int = 5,
):

    limit = max(
        1,
        min(
            limit,
            10,
        ),
    )

    response = await gmail_request(
        "GET",
        (
            "https://gmail.googleapis.com/"
            "gmail/v1/users/me/messages"
        ),
        params={
            "maxResults": limit,
        },
    )

    if response.status_code != 200:

        print(
            "Gmail list error:",
            response.status_code,
        )

        raise HTTPException(
            status_code=response.status_code,
            detail=(
                "Failed to fetch Gmail messages"
            ),
        )

    message_refs = (
        response
        .json()
        .get(
            "messages",
            [],
        )
    )

    messages = []

    for message_ref in message_refs:

        message_id = message_ref.get(
            "id"
        )

        if not message_id:

            continue

        detail_response = await gmail_request(
            "GET",
            (
                "https://gmail.googleapis.com/"
                "gmail/v1/users/me/messages/"
                + message_id
            ),
            params={
                "format": "metadata",

                "metadataHeaders": [
                    "From",
                    "To",
                    "Subject",
                    "Date",
                ],
            },
        )

        if (
            detail_response.status_code
            != 200
        ):

            continue

        data = detail_response.json()

        payload = data.get(
            "payload",
            {},
        )

        headers = payload.get(
            "headers",
            [],
        )

        messages.append(
            {
                "id": message_id,

                "thread_id": data.get(
                    "threadId"
                ),

                "from": get_header(
                    headers,
                    "From",
                ),

                "to": get_header(
                    headers,
                    "To",
                ),

                "subject": get_header(
                    headers,
                    "Subject",
                ),

                "date": get_header(
                    headers,
                    "Date",
                ),

                "snippet": repair_mojibake(
                    data.get(
                        "snippet",
                        "",
                    )
                ),
            }
        )

    return messages


# =========================================================
# Gmail Messages Endpoint
# =========================================================

@app.get(
    "/gmail/messages"
)
async def gmail_messages(
    max_results: int = 10,
):

    messages = await get_gmail_summaries(
        max_results
    )

    return {
        "count": len(
            messages
        ),

        "messages": messages,
    }


# =========================================================
# Detect Gmail Requests
# =========================================================

def is_gmail_request(
    user_message: str,
) -> bool:

    text = (
        user_message
        .lower()
        .strip()
    )

    gmail_keywords = [
        "gmail",
        "جيميل",
        "البريد",
        "بريدي",
        "الايميل",
        "الإيميل",
        "ايميلي",
        "إيميلي",
        "رسائلي",
        "رسائل البريد",
        "افحص البريد",
        "افحص gmail",
        "افحص جيميل",
        "اخر رسائلي",
        "آخر رسائلي",
        "لخص رسائلي",
        "لخّص رسائلي",
    ]

    return any(
        keyword in text
        for keyword in gmail_keywords
    )


# =========================================================
# Build Agent Reply
# =========================================================

async def build_agent_reply(
    user_message: str,
    user_id: str = "",
) -> str:

    # =====================================================
    # Gmail Request
    # =====================================================

    if is_gmail_request(
        user_message
    ):

        try:

            print(
                "Gmail request detected"
            )

            messages = (
                await get_gmail_summaries(
                    limit=5
                )
            )

            if not messages:

                return (
                    "لم أجد رسائل في Gmail حالياً."
                )

            message_blocks = []

            for index, message in enumerate(
                messages,
                start=1,
            ):

                message_blocks.append(
                    (
                        f"رسالة رقم {index}\n"
                        f"المرسل: "
                        f"{message.get('from', '')}\n"
                        f"العنوان: "
                        f"{message.get('subject', '')}\n"
                        f"التاريخ: "
                        f"{message.get('date', '')}\n"
                        f"المقتطف: "
                        f"{message.get('snippet', '')}"
                    )
                )

            gmail_context = "\n\n".join(
                message_blocks
            )

            conversation_context = ""

            if user_id:

                conversation_context = (
                    await build_conversation_context(
                        user_id
                    )
                )

            prompt = f"""
أنت مساعد أمير الشخصي.

طلب المستخدم الحالي:
{user_message}

هذه بيانات حقيقية تم جلبها الآن مباشرة من Gmail:

{gmail_context}

سجل المحادثة السابق إن وجد:
{conversation_context}

تعليمات مهمة جداً:

- بيانات الرسائل أعلاه جاءت فعلياً من Gmail.
- لا تقل إنك لا تستطيع الوصول إلى Gmail.
- لا تخترع أي رسالة أو مرسل أو عنوان.
- لا ترسل أي بريد.
- لا ترد على أي بريد.
- لا تحذف أي بريد.
- لا تعدل أي بريد.
- Gmail للقراءة فقط.
- إذا طلب المستخدم آخر رسالتين فقط، اعرض رسالتين فقط.
- إذا طلب أسماء المرسلين والعناوين فقط، لا تعرض المقتطفات.
- إذا طلب ملخصاً، لخّص الرسائل الموجودة فقط.
- أجب بالعربية بشكل واضح ومختصر.
"""

            reply = await run_agent(
                prompt
            )

            if not reply:

                return (
                    "تم جلب رسائل Gmail، "
                    "لكن تعذر إنشاء الملخص."
                )

            return reply

        except HTTPException as exc:

            print(
                "Gmail HTTP error:",
                exc.status_code,
            )

            if exc.status_code == 401:

                return (
                    "تعذر الوصول إلى Gmail حالياً. "
                    "قد تحتاج إلى إعادة ربط حساب Google."
                )

            return (
                "حدث خطأ أثناء قراءة Gmail. "
                "حاول مرة أخرى بعد قليل."
            )

        except Exception as exc:

            print(
                "Gmail processing error:",
                repr(exc),
            )

            return (
                "حدث خطأ أثناء فحص Gmail. "
                "لم يتم إرسال أو حذف أو تعديل أي بريد."
            )

    # =====================================================
    # Normal Conversation
    # =====================================================

    try:

        conversation_context = ""

        if user_id:

            conversation_context = (
                await build_conversation_context(
                    user_id
                )
            )

        if conversation_context:

            prompt = f"""
أنت مساعد أمير الشخصي.

سجل المحادثة السابق:
{conversation_context}

رسالة المستخدم الحالية:
{user_message}

أجب بالعربية بشكل طبيعي وواضح.
"""

            return await run_agent(
                prompt
            )

        return await run_agent(
            user_message
        )

    except Exception as exc:

        print(
            "Agent reply error:",
            repr(exc),
        )

        return (
            "حدث خطأ مؤقت أثناء معالجة طلبك. "
            "حاول مرة أخرى."
        )


# =========================================================
# Chat API
# =========================================================

@app.post(
    "/chat"
)
async def chat(
    request: ChatRequest,
):

    user_message = (
        request.message.strip()
    )

    if not user_message:

        raise HTTPException(
            status_code=400,
            detail=(
                "Message is required"
            ),
        )

    answer = await build_agent_reply(
        user_message,
        "web-user",
    )

    await save_memory(
        "web-user",
        "user",
        user_message,
    )

    await save_memory(
        "web-user",
        "assistant",
        answer,
    )

    return {
        "reply": answer,
    }


# =========================================================
# Send WhatsApp Message
# =========================================================

async def send_whatsapp_message(
    to: str,
    text: str,
):

    if (
        not WHATSAPP_ACCESS_TOKEN
        or not WHATSAPP_PHONE_NUMBER_ID
    ):

        print(
            "WhatsApp is not configured"
        )

        return False

    if not text:

        text = (
            "تعذر إنشاء الرد."
        )

    url = (
        "https://graph.facebook.com/v20.0/"
        + WHATSAPP_PHONE_NUMBER_ID
        + "/messages"
    )

    headers = {
        "Authorization": (
            "Bearer "
            + WHATSAPP_ACCESS_TOKEN
        ),

        "Content-Type": (
            "application/json"
        ),
    }

    payload = {
        "messaging_product": "whatsapp",

        "to": to,

        "type": "text",

        "text": {
            "body": text[:4000],
        },
    }

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:

        response = await client.post(
            url,
            headers=headers,
            json=payload,
        )

    if response.status_code >= 300:

        print(
            "WhatsApp send error:",
            response.status_code,
        )

        return False

    print(
        "WhatsApp reply sent successfully"
    )

    return True


# =========================================================
# WhatsApp Background Processing
# =========================================================

async def process_whatsapp_message(
    sender: str,
    text: str,
    message_id: str,
):

    try:

        print(
            "Processing WhatsApp message:",
            message_id,
        )

        answer = await build_agent_reply(
            text,
            sender,
        )

        await save_memory(
            sender,
            "user",
            text,
        )

        await save_memory(
            sender,
            "assistant",
            answer,
        )

        await send_whatsapp_message(
            sender,
            answer,
        )

    except Exception as exc:

        print(
            "WhatsApp processing error:",
            repr(exc),
        )

        # Always try to return a useful error message
        # instead of leaving the user without a reply.

        try:

            await send_whatsapp_message(
                sender,
                (
                    "حدث خطأ أثناء معالجة طلبك. "
                    "حاول مرة أخرى بعد قليل."
                ),
            )

        except Exception:

            pass


# =========================================================
# WhatsApp Verification
# =========================================================

@app.get(
    "/whatsapp/webhook"
)
def verify_whatsapp_webhook(
    request: Request,
):

    params = request.query_params

    mode = params.get(
        "hub.mode"
    )

    token = params.get(
        "hub.verify_token"
    )

    challenge = params.get(
        "hub.challenge"
    )

    if (
        mode == "subscribe"
        and token == WHATSAPP_VERIFY_TOKEN
    ):

        return PlainTextResponse(
            challenge or ""
        )

    raise HTTPException(
        status_code=403,
        detail=(
            "Verification failed"
        ),
    )


# =========================================================
# WhatsApp Webhook
# =========================================================

@app.post(
    "/whatsapp/webhook"
)
async def whatsapp_webhook(
    request: Request,
    background_tasks: BackgroundTasks,
):

    try:

        payload = await request.json()

        entries = payload.get(
            "entry",
            [],
        )

        for entry in entries:

            changes = entry.get(
                "changes",
                [],
            )

            for change in changes:

                value = change.get(
                    "value",
                    {},
                )

                messages = value.get(
                    "messages",
                    [],
                )

                if not messages:

                    continue

                for message in messages:

                    if (
                        message.get(
                            "type"
                        )
                        != "text"
                    ):

                        continue

                    message_id = message.get(
                        "id",
                        "",
                    )

                    if (
                        message_id
                        and not remember_whatsapp_message(
                            message_id
                        )
                    ):

                        print(
                            "Duplicate WhatsApp "
                            "message ignored:",
                            message_id,
                        )

                        continue

                    sender = message.get(
                        "from",
                        "",
                    )

                    text = (
                        message
                        .get(
                            "text",
                            {},
                        )
                        .get(
                            "body",
                            "",
                        )
                        .strip()
                    )

                    if not sender:

                        continue

                    if not text:

                        continue

                    background_tasks.add_task(
                        process_whatsapp_message,
                        sender,
                        text,
                        message_id,
                    )

    except Exception as exc:

        print(
            "WhatsApp webhook error:",
            repr(exc),
        )

    # Return quickly to Meta
    return {
        "status": "received"
    }


# =========================================================
# Local / Render
# =========================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "8000",
            )
        ),
    )