import os
import re
import secrets
from collections import deque
from email.header import decode_header
from urllib.parse import urlencode

import asyncpg
import httpx
from dotenv import load_dotenv
from fastapi import BackgroundTasks, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, PlainTextResponse, RedirectResponse
from pydantic import BaseModel

from agent import run_agent


# =========================================================
# App
# =========================================================

load_dotenv()

app = FastAPI(title="Amir Personal AI")


# =========================================================
# Environment Variables
# =========================================================

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REFRESH_TOKEN = os.getenv("GOOGLE_REFRESH_TOKEN")

WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
WHATSAPP_VERIFY_TOKEN = os.getenv(
    "WHATSAPP_VERIFY_TOKEN",
    "amir_personal_ai_verify_2026",
)

DATABASE_URL = os.getenv("DATABASE_URL")

RENDER_EXTERNAL_URL = os.getenv(
    "RENDER_EXTERNAL_URL",
    "https://amir-personal-ai-agent.onrender.com",
).rstrip("/")

REDIRECT_URI = (
    RENDER_EXTERNAL_URL
    + "/auth/google/callback"
)

GMAIL_SCOPE = (
    "https://www.googleapis.com/auth/gmail.readonly"
)


# =========================================================
# Temporary State
# =========================================================

pending_states = set()

google_tokens = {}

# الرسائل التي تنتظر موافقة المستخدم قبل الإرسال
pending_outbound_messages = {}


# =========================================================
# Database
# =========================================================

db_pool = None


async def connect_database():
    global db_pool

    if not DATABASE_URL:
        print("DATABASE_URL is not configured")
        return

    try:
        db_pool = await asyncpg.create_pool(
            dsn=DATABASE_URL,
            min_size=1,
            max_size=3,
            command_timeout=30,
        )

        async with db_pool.acquire() as conn:
            await conn.execute(
                """
                create table if not exists agent_memory (
                    id bigint generated by default
                    as identity primary key,

                    phone_number text not null,

                    role text not null,

                    content text not null,

                    created_at timestamptz
                    default now()
                );
                """
            )

            await conn.execute(
                """
                create index if not exists
                idx_agent_memory_phone

                on agent_memory (
                    phone_number,
                    created_at desc
                );
                """
            )

        print("Supabase database connected successfully")

    except Exception as exc:
        db_pool = None
        print(
            "Database connection error:",
            repr(exc),
        )


@app.on_event("startup")
async def startup_event():
    await connect_database()


@app.on_event("shutdown")
async def shutdown_event():
    global db_pool

    if db_pool:
        await db_pool.close()
        db_pool = None


# =========================================================
# Persistent Memory
# =========================================================

MAX_CONVERSATION_MESSAGES = 20


async def save_memory(
    user_id: str,
    role: str,
    content: str,
):
    if not user_id or not role or not content:
        return

    if not db_pool:
        return

    try:
        async with db_pool.acquire() as conn:
            await conn.execute(
                """
                insert into agent_memory (
                    phone_number,
                    role,
                    content
                )
                values ($1, $2, $3)
                """,
                user_id,
                role,
                content,
            )

    except Exception as exc:
        print(
            "Memory save error:",
            repr(exc),
        )


async def get_memory(
    user_id: str,
    limit: int = MAX_CONVERSATION_MESSAGES,
):
    if not user_id or not db_pool:
        return []

    try:
        async with db_pool.acquire() as conn:
            rows = await conn.fetch(
                """
                select
                    role,
                    content,
                    created_at

                from agent_memory

                where phone_number = $1

                order by created_at desc

                limit $2
                """,
                user_id,
                limit,
            )

        return [
            {
                "role": row["role"],
                "content": row["content"],
            }
            for row in reversed(rows)
        ]

    except Exception as exc:
        print(
            "Memory read error:",
            repr(exc),
        )

        return []


async def build_conversation_context(
    user_id: str,
) -> str:
    history = await get_memory(user_id)

    if not history:
        return ""

    lines = []

    for item in history:
        if item.get("role") == "user":
            label = "المستخدم"
        else:
            label = "المساعد"

        lines.append(
            f"{label}: {item.get('content', '')}"
        )

    return "\n".join(lines)


# =========================================================
# WhatsApp Helpers
# =========================================================

def normalize_phone_number(
    phone: str,
) -> str:
    """
    يحول:
    +970568042923
    إلى:
    970568042923
    """

    return re.sub(
        r"\D",
        "",
        phone or "",
    )


def parse_whatsapp_send_command(
    text: str,
):
    """
    أمثلة:

    أرسل إلى +970568042923 رسالة: مرحبا
    ارسل الى 970568042923: مرحبا
    أرسل ل +970568042923 مرحبا
    """

    text = (text or "").strip()

    pattern = (
        r"^(?:أرسل|ارسل)\s+"
        r"(?:إلى|الى|ل|لـ)\s*"
        r"(\+?\d{8,15})"
        r"\s*(?:رسالة)?\s*[:：]?\s*"
        r"(.+)$"
    )

    match = re.match(
        pattern,
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if not match:
        return None

    phone = normalize_phone_number(
        match.group(1)
    )

    message = match.group(2).strip()

    if not phone or not message:
        return None

    return phone, message


# =========================================================
# WhatsApp duplicate protection
# =========================================================

MAX_PROCESSED_WHATSAPP_MESSAGES = 1000

processed_whatsapp_message_ids = set()

processed_whatsapp_message_order = deque()


def remember_whatsapp_message(
    message_id: str,
) -> bool:
    if not message_id:
        return True

    if message_id in processed_whatsapp_message_ids:
        return False

    processed_whatsapp_message_ids.add(
        message_id
    )

    processed_whatsapp_message_order.append(
        message_id
    )

    while (
        len(processed_whatsapp_message_order)
        > MAX_PROCESSED_WHATSAPP_MESSAGES
    ):
        oldest = (
            processed_whatsapp_message_order
            .popleft()
        )

        processed_whatsapp_message_ids.discard(
            oldest
        )

    return True


# =========================================================
# WhatsApp Actual Sender
# =========================================================

async def send_whatsapp_message(
    to: str,
    text: str,
) -> bool:
    if (
        not WHATSAPP_ACCESS_TOKEN
        or not WHATSAPP_PHONE_NUMBER_ID
    ):
        print(
            "WhatsApp configuration missing"
        )
        return False

    to = normalize_phone_number(to)

    if not to or not text:
        return False

    url = (
        "https://graph.facebook.com/v20.0/"
        + WHATSAPP_PHONE_NUMBER_ID
        + "/messages"
    )

    headers = {
        "Authorization": (
            "Bearer "
            + WHATSAPP_ACCESS_TOKEN
        ),
        "Content-Type": "application/json",
    }

    payload = {
        "messaging_product": "whatsapp",
        "recipient_type": "individual",
        "to": to,
        "type": "text",
        "text": {
            "preview_url": False,
            "body": text[:4000],
        },
    }

    try:
        async with httpx.AsyncClient(
            timeout=30.0
        ) as client:
            response = await client.post(
                url,
                headers=headers,
                json=payload,
            )

        if response.status_code >= 300:
            print(
                "WhatsApp send FAILED:",
                response.status_code,
                response.text[:1000],
            )
            return False

        print(
            "WhatsApp message sent successfully to:",
            to,
        )

        print(
            "Meta response:",
            response.text[:500],
        )

        return True

    except Exception as exc:
        print(
            "WhatsApp send exception:",
            repr(exc),
        )

        return False


# =========================================================
# Models
# =========================================================

class ChatRequest(BaseModel):
    message: str


# =========================================================
# Root / Health
# =========================================================

@app.get("/")
def root():
    return {
        "name": "Amir Personal AI",
        "status": "online",
        "database": (
            "connected"
            if db_pool
            else "disconnected"
        ),
        "gmail_login": "/auth/google",
        "gmail_status": "/gmail/status",
        "gmail_messages": "/gmail/messages",
        "whatsapp_webhook": "/whatsapp/webhook",
        "health": "/health",
    }


@app.get("/health")
def health():
    return {
        "status": "ok",
        "database_connected": bool(db_pool),
        "gmail_refresh_token_configured": bool(
            GOOGLE_REFRESH_TOKEN
        ),
        "whatsapp_configured": bool(
            WHATSAPP_ACCESS_TOKEN
            and WHATSAPP_PHONE_NUMBER_ID
        ),
    }


# =========================================================
# Privacy
# =========================================================

@app.get(
    "/privacy",
    response_class=HTMLResponse,
)
def privacy():
    return """
    <!doctype html>
    <html lang="ar" dir="rtl">
    <head>
        <meta charset="utf-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
        >
        <title>سياسة الخصوصية</title>
    </head>

    <body style="
        font-family:Arial;
        max-width:800px;
        margin:40px auto;
        padding:20px;
        line-height:1.8;
    ">
        <h1>سياسة الخصوصية</h1>

        <p>
            يستخدم التطبيق Google OAuth
            للوصول إلى Gmail بإذن المستخدم.
        </p>

        <p>
            الوصول إلى Gmail للقراءة فقط.
        </p>

        <p>
            يستخدم التطبيق WhatsApp Cloud API
            لاستقبال وإرسال الرسائل.
        </p>

        <p>
            قد يتم حفظ سجل المحادثة
            لتوفير ذاكرة للمساعد.
        </p>
    </body>
    </html>
    """


# =========================================================
# Terms
# =========================================================

@app.get(
    "/terms",
    response_class=HTMLResponse,
)
def terms():
    return """
    <!doctype html>
    <html lang="ar" dir="rtl">
    <head>
        <meta charset="utf-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
        >
        <title>شروط الاستخدام</title>
    </head>

    <body style="
        font-family:Arial;
        max-width:800px;
        margin:40px auto;
        padding:20px;
        line-height:1.8;
    ">
        <h1>شروط الاستخدام</h1>

        <p>
            هذا التطبيق مساعد شخصي
            للمستخدمين المصرح لهم.
        </p>
    </body>
    </html>
    """


# =========================================================
# Gmail Helpers
# =========================================================

def decode_mime_header(
    value: str,
) -> str:
    if not value:
        return ""

    try:
        parts = decode_header(value)

        result = ""

        for part, encoding in parts:
            if isinstance(part, bytes):
                result += part.decode(
                    encoding or "utf-8",
                    errors="replace",
                )
            else:
                result += part

        return result

    except Exception:
        return value


def repair_mojibake(
    text: str,
) -> str:
    if not text:
        return ""

    candidates = [text]

    for source_encoding in [
        "latin1",
        "cp1252",
    ]:
        try:
            fixed = (
                text
                .encode(
                    source_encoding,
                    errors="ignore",
                )
                .decode(
                    "utf-8",
                    errors="ignore",
                )
            )

            if fixed:
                candidates.append(fixed)

        except Exception:
            pass

    def score(value: str) -> int:
        bad = (
            value.count("Ø")
            + value.count("Ù")
            + value.count("Ã")
            + value.count("�")
        )

        arabic = sum(
            1
            for char in value
            if "\u0600"
            <= char
            <= "\u06ff"
        )

        return (
            arabic * 3
            - bad * 5
        )

    return max(
        candidates,
        key=score,
    )


def clean_header(
    value: str,
) -> str:
    return repair_mojibake(
        decode_mime_header(value)
    )


def get_header(
    headers: list,
    name: str,
) -> str:
    for header in headers:
        if (
            header
            .get("name", "")
            .lower()
            == name.lower()
        ):
            return clean_header(
                header.get("value", "")
            )

    return ""


# =========================================================
# Google OAuth
# =========================================================

async def refresh_access_token() -> str:
    refresh_token = (
        google_tokens.get(
            "refresh_token"
        )
        or GOOGLE_REFRESH_TOKEN
    )

    if not refresh_token:
        raise HTTPException(
            status_code=401,
            detail="Connect Gmail first",
        )

    if (
        not GOOGLE_CLIENT_ID
        or not GOOGLE_CLIENT_SECRET
    ):
        raise HTTPException(
            status_code=500,
            detail=(
                "Google OAuth is not configured"
            ),
        )

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:
        response = await client.post(
            "https://oauth2.googleapis.com/token",
            data={
                "client_id": (
                    GOOGLE_CLIENT_ID
                ),
                "client_secret": (
                    GOOGLE_CLIENT_SECRET
                ),
                "refresh_token": (
                    refresh_token
                ),
                "grant_type": (
                    "refresh_token"
                ),
            },
        )

    if response.status_code != 200:
        print(
            "Google token refresh failed:",
            response.status_code,
            response.text[:300],
        )

        raise HTTPException(
            status_code=401,
            detail="تعذر تجديد جلسة Gmail",
        )

    data = response.json()

    access_token = data.get(
        "access_token"
    )

    if not access_token:
        raise HTTPException(
            status_code=401,
            detail=(
                "Google access token missing"
            ),
        )

    google_tokens[
        "access_token"
    ] = access_token

    google_tokens[
        "refresh_token"
    ] = refresh_token

    return access_token


async def get_access_token() -> str:
    token = google_tokens.get(
        "access_token"
    )

    if token:
        return token

    return await refresh_access_token()


@app.get("/auth/google")
def google_login():
    if not GOOGLE_CLIENT_ID:
        raise HTTPException(
            status_code=500,
            detail="GOOGLE_CLIENT_ID missing",
        )

    state = secrets.token_urlsafe(32)

    pending_states.add(state)

    params = {
        "client_id": GOOGLE_CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "response_type": "code",
        "scope": GMAIL_SCOPE,
        "access_type": "offline",
        "prompt": "consent",
        "state": state,
    }

    url = (
        "https://accounts.google.com/"
        "o/oauth2/v2/auth?"
        + urlencode(params)
    )

    return RedirectResponse(url)


@app.get(
    "/auth/google/callback"
)
async def google_callback(
    code: str,
    state: str,
):
    if state not in pending_states:
        raise HTTPException(
            status_code=400,
            detail="Invalid OAuth state",
        )

    pending_states.remove(state)

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:
        response = await client.post(
            "https://oauth2.googleapis.com/token",
            data={
                "client_id": (
                    GOOGLE_CLIENT_ID
                ),
                "client_secret": (
                    GOOGLE_CLIENT_SECRET
                ),
                "code": code,
                "grant_type": (
                    "authorization_code"
                ),
                "redirect_uri": (
                    REDIRECT_URI
                ),
            },
        )

    if response.status_code != 200:
        print(
            "Google authorization failed:",
            response.status_code,
            response.text[:300],
        )

        raise HTTPException(
            status_code=400,
            detail=(
                "Google authorization failed"
            ),
        )

    data = response.json()

    access_token = data.get(
        "access_token"
    )

    refresh_token = data.get(
        "refresh_token"
    )

    if access_token:
        google_tokens[
            "access_token"
        ] = access_token

    if refresh_token:
        google_tokens[
            "refresh_token"
        ] = refresh_token

    return PlainTextResponse(
        "Gmail connected successfully"
    )


# =========================================================
# Gmail API Helper
# =========================================================

async def gmail_request(
    method: str,
    url: str,
    **kwargs,
):
    token = await get_access_token()

    headers = kwargs.pop(
        "headers",
        {},
    )

    headers[
        "Authorization"
    ] = f"Bearer {token}"

    async with httpx.AsyncClient(
        timeout=30.0
    ) as client:
        response = await client.request(
            method,
            url,
            headers=headers,
            **kwargs,
        )

    if response.status_code == 401:
        google_tokens.pop(
            "access_token",
            None,
        )

        token = await refresh_access_token()

        headers[
            "Authorization"
        ] = f"Bearer {token}"

        async with httpx.AsyncClient(
            timeout=30.0
        ) as client:
            response = await client.request(
                method,
                url,
                headers=headers,
                **kwargs,
            )

    return response


# =========================================================
# Gmail Status
# =========================================================

@app.get("/gmail/status")
async def gmail_status():
    try:
        response = await gmail_request(
            "GET",
            (
                "https://gmail.googleapis.com/"
                "gmail/v1/users/me/profile"
            ),
        )

        if response.status_code != 200:
            return {
                "connected": False,
                "status_code": (
                    response.status_code
                ),
                "persistent_refresh_token": bool(
                    GOOGLE_REFRESH_TOKEN
                ),
            }

        data = response.json()

        return {
            "connected": True,
            "email": data.get(
                "emailAddress"
            ),
            "persistent_refresh_token": bool(
                GOOGLE_REFRESH_TOKEN
            ),
        }

    except Exception as exc:
        print(
            "Gmail status error:",
            repr(exc),
        )

        return {
            "connected": False,
            "persistent_refresh_token": bool(
                GOOGLE_REFRESH_TOKEN
            ),
        }


# =========================================================
# Gmail Messages
# =========================================================

async def get_gmail_summaries(
    limit: int = 5,
):
    limit = max(
        1,
        min(limit, 10),
    )

    response = await gmail_request(
        "GET",
        (
            "https://gmail.googleapis.com/"
            "gmail/v1/users/me/messages"
        ),
        params={
            "maxResults": limit,
        },
    )

    if response.status_code != 200:
        raise HTTPException(
            status_code=(
                response.status_code
            ),
            detail=(
                "Failed to fetch Gmail"
            ),
        )

    refs = (
        response
        .json()
        .get(
            "messages",
            [],
        )
    )

    messages = []

    for item in refs:
        message_id = item.get("id")

        if not message_id:
            continue

        detail = await gmail_request(
            "GET",
            (
                "https://gmail.googleapis.com/"
                "gmail/v1/users/me/messages/"
                + message_id
            ),
            params={
                "format": "metadata",
                "metadataHeaders": [
                    "From",
                    "To",
                    "Subject",
                    "Date",
                ],
            },
        )

        if detail.status_code != 200:
            continue

        data = detail.json()

        payload = data.get(
            "payload",
            {},
        )

        headers = payload.get(
            "headers",
            [],
        )

        messages.append(
            {
                "id": message_id,
                "thread_id": data.get(
                    "threadId"
                ),
                "from": get_header(
                    headers,
                    "From",
                ),
                "to": get_header(
                    headers,
                    "To",
                ),
                "subject": get_header(
                    headers,
                    "Subject",
                ),
                "date": get_header(
                    headers,
                    "Date",
                ),
                "snippet": repair_mojibake(
                    data.get(
                        "snippet",
                        "",
                    )
                ),
            }
        )

    return messages


@app.get("/gmail/messages")
async def gmail_messages(
    max_results: int = 10,
):
    messages = await get_gmail_summaries(
        max_results
    )

    return {
        "count": len(messages),
        "messages": messages,
    }


# =========================================================
# Gmail Request Detection
# =========================================================

def is_gmail_request(
    text: str,
) -> bool:
    text = (
        text
        or ""
    ).lower()

    keywords = [
        "gmail",
        "جيميل",
        "البريد",
        "بريدي",
        "الايميل",
        "الإيميل",
        "رسائلي",
        "رسائل البريد",
        "افحص البريد",
        "افحص gmail",
        "افحص جيميل",
        "آخر رسائلي",
        "اخر رسائلي",
        "لخص رسائلي",
        "لخّص رسائلي",
    ]

    return any(
        word in text
        for word in keywords
    )


# =========================================================
# Main Agent Logic
# =========================================================

async def build_agent_reply(
    user_message: str,
    user_id: str = "",
) -> str:

    user_message = (
        user_message
        or ""
    ).strip()

    normalized_command = (
        user_message.lower()
    )

    pending = (
        pending_outbound_messages
        .get(user_id)
    )

    # =====================================================
    # Confirm Pending WhatsApp Send
    # =====================================================

    confirmation_words = [
        "موافق",
        "وافق",
        "نعم",
        "نعم ارسل",
        "نعم أرسل",
        "ارسل",
        "أرسل",
        "تأكيد",
        "تاكيد",
        "اكد",
        "أكد",
        "موافق ارسل",
        "موافق أرسل",
        "موافق ارسل الرسالة",
        "موافق أرسل الرسالة",
        "نعم ارسلها",
        "نعم أرسلها",
        "confirm",
    ]

    is_confirmation = any(
        (
            normalized_command == word
            or normalized_command.startswith(
                word + " "
            )
        )
        for word in confirmation_words
    )

    if pending and is_confirmation:
        to_number = pending.get("to")
        message_text = pending.get("text")

        print(
            "User confirmed outbound WhatsApp:",
            user_id,
            "to:",
            to_number,
        )

        success = await send_whatsapp_message(
            to_number,
            message_text,
        )

        if success:
            pending_outbound_messages.pop(
                user_id,
                None,
            )

            return (
                "تم إرسال الرسالة بنجاح ✅\n\n"
                f"إلى: +{to_number}"
            )

        return (
            "حاولت إرسال الرسالة ولكن "
            "WhatsApp رفض الإرسال ❌\n\n"
            "اكتب «موافق» للمحاولة مرة أخرى "
            "أو «إلغاء»."
        )

    # =====================================================
    # Cancel Pending Send
    # =====================================================

    cancel_words = [
        "إلغاء",
        "الغاء",
        "ألغي",
        "الغي",
        "إلغي",
        "cancel",
    ]

    if (
        pending
        and normalized_command
        in cancel_words
    ):
        pending_outbound_messages.pop(
            user_id,
            None,
        )

        return (
            "تم إلغاء إرسال الرسالة ✅"
        )

    # =====================================================
    # Create New Outbound Send
    # =====================================================

    outbound = parse_whatsapp_send_command(
        user_message
    )

    if outbound:
        to_number, message_text = outbound

        if (
            len(to_number) < 8
            or len(to_number) > 15
        ):
            return (
                "رقم الهاتف غير صحيح.\n\n"
                "اكتب الرقم بالصيغة الدولية.\n"
                "مثال:\n"
                "+9705XXXXXXXX"
            )

        if not message_text:
            return (
                "لم تكتب نص الرسالة."
            )

        if len(message_text) > 3500:
            return (
                "الرسالة طويلة جدًا. "
                "اختصرها ثم حاول مرة أخرى."
            )

        pending_outbound_messages[
            user_id
        ] = {
            "to": to_number,
            "text": message_text,
        }

        print(
            "Outbound WhatsApp pending:",
            user_id,
            "to:",
            to_number,
        )

        return (
            "جاهز للإرسال 📤\n\n"
            f"إلى: +{to_number}\n\n"
            "الرسالة:\n"
            f"{message_text}\n\n"
            "لم يتم الإرسال بعد.\n\n"
            "اكتب «موافق» للإرسال "
            "أو «إلغاء» لإلغاء العملية."
        )

    # =====================================================
    # Gmail
    # =====================================================

    if is_gmail_request(user_message):
        try:
            messages = await get_gmail_summaries(
                limit=5
            )

            if not messages:
                return (
                    "لم أجد رسائل في Gmail."
                )

            blocks = []

            for index, item in enumerate(
                messages,
                start=1,
            ):
                blocks.append(
                    (
                        f"رسالة {index}\n"
                        f"المرسل: "
                        f"{item.get('from', '')}\n"
                        f"العنوان: "
                        f"{item.get('subject', '')}\n"
                        f"التاريخ: "
                        f"{item.get('date', '')}\n"
                        f"المقتطف: "
                        f"{item.get('snippet', '')}"
                    )
                )

            gmail_context = "\n\n".join(
                blocks
            )

            memory_context = ""

            if user_id:
                memory_context = (
                    await build_conversation_context(
                        user_id
                    )
                )

            prompt = f"""
أنت وكيل أمير الشخصي.

طلب المستخدم:
{user_message}

هذه بيانات حقيقية تم جلبها الآن من Gmail:
{gmail_context}

المحادثة السابقة:
{memory_context}

تعليمات مهمة:
- استخدم بيانات Gmail الموجودة أعلاه فقط.
- لا تخترع رسائل أو مرسلين.
- لا ترسل أي بريد.
- لا تحذف أي بريد.
- لا تعدل أي بريد.
- Gmail للقراءة فقط.
- إذا طلب آخر رسالتين فقط، اعرض رسالتين فقط.
- إذا طلب اسم المرسل والعنوان فقط، اعرضهما فقط.
- أجب بالعربية بشكل واضح ومختصر.
"""

            reply = await run_agent(prompt)

            return (
                reply
                or (
                    "تم جلب Gmail ولكن "
                    "تعذر إنشاء الرد."
                )
            )

        except Exception as exc:
            print(
                "Gmail processing error:",
                repr(exc),
            )

            return (
                "حدث خطأ أثناء فحص Gmail. "
                "لم يتم إرسال أو حذف أي بريد."
            )

    # =====================================================
    # Normal AI Conversation
    # =====================================================

    try:
        context = ""

        if user_id:
            context = (
                await build_conversation_context(
                    user_id
                )
            )

        prompt = f"""
أنت وكيل أمير الشخصي.

المحادثة السابقة:
{context}

رسالة المستخدم الحالية:
{user_message}

تعليمات:
- أجب بالعربية بشكل طبيعي وواضح.
- لا تدّع أنك أرسلت WhatsApp إلا إذا قام النظام بتنفيذ الإرسال فعليًا.
- إذا أراد المستخدم إرسال رسالة WhatsApp، اطلب منه استخدام الصيغة:
  أرسل إلى +رقم_الهاتف رسالة: نص الرسالة
- بعد إنشاء طلب الإرسال، يحتاج إلى كتابة «موافق».
- لا تقل إن WhatsApp غير متاح بشكل عام، لأن التطبيق يحتوي على وظيفة إرسال حقيقية.
"""

        reply = await run_agent(prompt)

        return (
            reply
            or "تعذر إنشاء الرد."
        )

    except Exception as exc:
        print(
            "Agent error:",
            repr(exc),
        )

        return (
            "حدث خطأ مؤقت أثناء معالجة طلبك."
        )


# =========================================================
# Web Chat API
# =========================================================

@app.post("/chat")
async def chat(
    request: ChatRequest,
):
    text = request.message.strip()

    if not text:
        raise HTTPException(
            status_code=400,
            detail="Message is required",
        )

    answer = await build_agent_reply(
        text,
        "web-user",
    )

    await save_memory(
        "web-user",
        "user",
        text,
    )

    await save_memory(
        "web-user",
        "assistant",
        answer,
    )

    return {
        "reply": answer
    }


# =========================================================
# IMPORTANT FIX:
# WhatsApp Incoming Message Processor
# =========================================================

async def process_whatsapp_message(
    sender: str,
    text: str,
    message_id: str,
):
    """
    هذه هي الدالة التي كانت مفقودة.

    تستقبل رسالة المستخدم من Meta،
    ترسلها إلى الوكيل،
    تحفظ المحادثة،
    ثم تعيد رد الوكيل إلى المستخدم.
    """

    try:
        print(
            "Processing WhatsApp message:",
            message_id,
            "from:",
            sender,
        )

        answer = await build_agent_reply(
            text,
            sender,
        )

        await save_memory(
            sender,
            "user",
            text,
        )

        await save_memory(
            sender,
            "assistant",
            answer,
        )

        reply_success = (
            await send_whatsapp_message(
                sender,
                answer,
            )
        )

        if reply_success:
            print(
                "Agent WhatsApp reply sent successfully"
            )
        else:
            print(
                "Agent WhatsApp reply failed"
            )

    except Exception as exc:
        print(
            "WhatsApp processing error:",
            repr(exc),
        )

        try:
            await send_whatsapp_message(
                sender,
                (
                    "حدث خطأ أثناء معالجة طلبك. "
                    "حاول مرة أخرى بعد قليل."
                ),
            )

        except Exception as send_exc:
            print(
                "Fallback WhatsApp send failed:",
                repr(send_exc),
            )


# =========================================================
# WhatsApp Webhook Verification
# =========================================================

@app.get("/whatsapp/webhook")
def verify_whatsapp_webhook(
    request: Request,
):
    mode = request.query_params.get(
        "hub.mode"
    )

    token = request.query_params.get(
        "hub.verify_token"
    )

    challenge = request.query_params.get(
        "hub.challenge"
    )

    if (
        mode == "subscribe"
        and token == WHATSAPP_VERIFY_TOKEN
    ):
        return PlainTextResponse(
            challenge or ""
        )

    raise HTTPException(
        status_code=403,
        detail="Verification failed",
    )


# =========================================================
# WhatsApp Webhook Receiver
# =========================================================

@app.post("/whatsapp/webhook")
async def whatsapp_webhook(
    request: Request,
    background_tasks: BackgroundTasks,
):
    try:
        payload = await request.json()

        entries = payload.get(
            "entry",
            [],
        )

        for entry in entries:
            changes = entry.get(
                "changes",
                [],
            )

            for change in changes:
                value = change.get(
                    "value",
                    {},
                )

                messages = value.get(
                    "messages",
                    [],
                )

                # status updates may contain no messages
                if not messages:
                    continue

                for message in messages:
                    if (
                        message.get("type")
                        != "text"
                    ):
                        continue

                    message_id = message.get(
                        "id",
                        "",
                    )

                    if (
                        message_id
                        and not remember_whatsapp_message(
                            message_id
                        )
                    ):
                        print(
                            "Duplicate WhatsApp message ignored:",
                            message_id,
                        )
                        continue

                    sender = message.get(
                        "from",
                        "",
                    )

                    text = (
                        message
                        .get(
                            "text",
                            {},
                        )
                        .get(
                            "body",
                            "",
                        )
                        .strip()
                    )

                    if not sender or not text:
                        continue

                    background_tasks.add_task(
                        process_whatsapp_message,
                        sender,
                        text,
                        message_id,
                    )

    except Exception as exc:
        print(
            "WhatsApp webhook error:",
            repr(exc),
        )

    # Meta must receive HTTP 200
    return {
        "status": "received"
    }


# =========================================================
# Run
# =========================================================

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "8000",
            )
        ),
    )